### ISSUE TITLE
About PySCIPOpt version 

### ISSUE THREAD

**Issue by only-changer** [Opt-Mucca/Adaptive-Cutsel-MILP#1]
Hi,
I find that PySCIPOpt version 4.1.0 requires python version 3.7+, but the requirement of this repo is 3.6?
Below is what I get from conda:

Specifications:

  - pyscipopt=4.1.0 -> python[version='3.10.*|3.7.*|3.9.*|3.8.*']
  - pyscipopt=4.1.0 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']

Your python: python=3.6

**Comment by Opt-Mucca** [comment]
Heyo,

Thanks for finding the repo and raising the issue! 

The python requirement is pretty interesting for conda, because I have never had trouble installing PySCIPOpt from source using 3.6.......
There are two fix options I would propose:

- I just tested the init_venv script by changing the following line in ```init_venv.sh```:
```virtualenv -p python3.6 venv``` to ```virtualenv -p python3.8 venv```
The script still works and installs the virtual environment succesfully, so I guess all the packaging versioning does carryover. You should then be able to install PySCIPOpt by conda.

- Install PySCIPOpt from source without using conda. (This may be more work)
